package poli14;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class Inregistrare_medic extends javax.swing.JFrame {

	/**
	 * Creates new form inregistrare
	 */
	public Inregistrare_medic() {
		initComponents();
		tabel_update();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtspec = new javax.swing.JTextField();
		txtgrad = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		txtcod = new javax.swing.JTextField();
		txtcomp = new javax.swing.JTextField();
		txttitlu = new javax.swing.JTextField();
		txtpost = new javax.swing.JTextField();
		txtprocent = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jLabel1.setText("Medic");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date personale",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

		jLabel2.setText("Specialitate");

		jLabel3.setText("Grad");

		txtspec.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtspecActionPerformed(evt);
			}
		});

		jButton1.setText("Adauga");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Sterge");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setText("Cod Parafa");

		jLabel6.setText("Competente");

		jLabel7.setText("Titlu Stiintific");

		jLabel8.setText("Post Didactic");

		jLabel9.setText("Procent Salariu");

		txtcomp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtcompActionPerformed(evt);
			}
		});

		jButton3.setText("Editeaza");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jButton1).addGap(18, 18, 18)
						.addComponent(jButton3).addGap(18, 18, 18).addComponent(jButton2).addGap(0, 0, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74,
														Short.MAX_VALUE)
												.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(77, 77, 77))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 65,
														Short.MAX_VALUE)
												.addGap(86, 86, 86))
										.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtgrad, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtspec, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txttitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtprocent, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16).addComponent(txtspec,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtgrad, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(24, 24, 24)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(txttitlu, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(txtprocent, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))));

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null } },
				new String[] { "idMedic", "Specialitate", "Grad", "Cod Parafa", "Competente", "Titlu Stiintific",
						"Post Didactic", "Procent Salariu" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
					java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.Integer.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable2MouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(jTable2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(259, 259, 259)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(738, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane2)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(18, 18, 18)
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(33, 33, 33)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	Connection con1;
	PreparedStatement insert;
	Statement statement;

	private void tabel_update() {
		int x;

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			insert = con1.prepareStatement("select* from medic");
			ResultSet rs = insert.executeQuery();
			ResultSetMetaData Rss = rs.getMetaData();
			x = Rss.getColumnCount();
			DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
			Df.setRowCount(0);

			while (rs.next()) {
				Vector v2 = new Vector();
				for (int i = 1; i <= x; i++) {
					v2.add(rs.getString("idMedic"));
					v2.add(rs.getString("Specialitate"));
					v2.add(rs.getString("Gradul"));
					v2.add(rs.getString("Cod_Parafa"));
					v2.add(rs.getString("Competente"));
					v2.add(rs.getString("Titlul_ST"));
					v2.add(rs.getString("Post_Didactic"));
					v2.add(rs.getString("Procent_Salariu"));

				}
				Df.addRow(v2);
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void txtspecActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String spec = txtspec.getText();
		String grad = txtgrad.getText();
		String cod = txtcod.getText();
		String comp = txtcomp.getText();
		String titlu = txttitlu.getText();
		String post = txtpost.getText();
		String procent = txtprocent.getText();

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			insert = con1.prepareStatement(
					"insert into medic(Specialitate,Gradul,Cod_Parafa,Competente,Titlul_ST,Post_Didactic,Procent_Salariu)values(?,?,?,?,?,?,?)");
			insert.setString(1, spec);
			insert.setString(2, grad);
			insert.setString(3, cod);// ordinea din tabele
			insert.setString(4, comp);
			insert.setString(5, titlu);
			insert.setString(6, post);
			insert.setString(7, procent);
			insert.executeUpdate();

			JOptionPane.showMessageDialog(this, "Adaugat");
			tabel_update();

			txtspec.setText("");
			txtgrad.setText("");
			txtcod.setText("");
			txtcomp.setText("");
			txttitlu.setText("");
			txtpost.setText("");
			txtprocent.setText("");

			txtspec.requestFocus();

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void txtcompActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
		int selectedIndex = jTable2.getSelectedRow();
		txtspec.setText(Df.getValueAt(selectedIndex, 1).toString());
		txtgrad.setText(Df.getValueAt(selectedIndex, 2).toString());
		txtcod.setText(Df.getValueAt(selectedIndex, 3).toString());
		txtcomp.setText(Df.getValueAt(selectedIndex, 4).toString());
		txttitlu.setText(Df.getValueAt(selectedIndex, 5).toString());
		txtpost.setText(Df.getValueAt(selectedIndex, 6).toString());
		txtprocent.setText(Df.getValueAt(selectedIndex, 7).toString());

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
		int selectedIndex = jTable2.getSelectedRow();

		try {

			int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
			String spec = txtspec.getText();
			String grad = txtgrad.getText();
			String cod = txtcod.getText();
			String comp = txtcomp.getText();
			String titlu = txttitlu.getText();
			String post = txtpost.getText();
			String procent = txtprocent.getText();

			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			insert = con1.prepareStatement(
					"update medic set spec= ?,grad=?,cod=?,comp=?,titlu=?,post=?,procent=? where id=?");
			insert.setString(1, spec);
			insert.setString(2, grad);
			insert.setString(3, cod);// ordinea din tabele
			insert.setString(4, comp);
			insert.setString(5, titlu);
			insert.setString(6, post);
			insert.setString(7, procent);
			insert.setInt(8, id);
			insert.executeUpdate();

			JOptionPane.showMessageDialog(this, "Actualizare date reusita!");
			tabel_update();

			txtspec.setText("");
			txtgrad.setText("");
			txtcod.setText("");
			txtcomp.setText("");
			txttitlu.setText("");
			txtpost.setText("");
			txtprocent.setText("");

			txtspec.requestFocus();

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
		int selectedIndex = jTable2.getSelectedRow();

		try {

			int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());

			int dialogResult = JOptionPane.showConfirmDialog(null, "Vrei sa stergi inregistrarea?", "Atentie!",
					JOptionPane.YES_NO_OPTION);
			if (dialogResult == JOptionPane.YES_OPTION) {

				Class.forName("com.mysql.jdbc.Driver");
				con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");

				statement = (Statement) con1.createStatement();
				String sql;
				ResultSet resultSet = statement.executeQuery(
						"SELECT  utilizator.CNP   FROM policlinica.medic inner join policlinica.angajat using (idMedic) inner join policlinica.utilizator using (idAngajat) where medic.idMedic = "
								+ id + ";");
				resultSet.next();
				statement.executeQuery("call drop_utilizator('" + resultSet.getString("CNP") + "');");

				JOptionPane.showMessageDialog(this, "Inregistrare stearsa cu succes!");
				tabel_update();

				txtspec.setText("");
				txtgrad.setText("");
				txtcod.setText("");
				txtcomp.setText("");
				txttitlu.setText("");
				txtpost.setText("");
				txtprocent.setText("");

				txtspec.requestFocus();

			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField txtcod;
	private javax.swing.JTextField txtcomp;
	private javax.swing.JTextField txtgrad;
	private javax.swing.JTextField txtpost;
	private javax.swing.JTextField txtprocent;
	private javax.swing.JTextField txtspec;
	private javax.swing.JTextField txttitlu;
	// End of variables declaration
}
