/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poli14;

/**
 *
 * @author ToBy
 */
public class Inspector extends javax.swing.JFrame {

	/**
	 * Creates new form Inspector
	 */
	public Inspector() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		cautare_angajat = new javax.swing.JButton();
		orar_angajat = new javax.swing.JButton();
		log_out = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(153, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
		jLabel1.setText("Inspector");

		cautare_angajat.setBackground(new java.awt.Color(153, 204, 255));
		cautare_angajat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		cautare_angajat.setText("Cautare Angajat");
		cautare_angajat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cautare_angajatActionPerformed(evt);
			}
		});

		orar_angajat.setBackground(new java.awt.Color(153, 204, 255));
		orar_angajat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		orar_angajat.setText("Orar Angajati");
		orar_angajat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				orar_angajatActionPerformed(evt);
			}
		});

		log_out.setBackground(new java.awt.Color(153, 204, 255));
		log_out.setText("Log out");
		log_out.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				log_outActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(28, 28, 28).addComponent(log_out)
										.addGap(211, 211, 211).addComponent(jLabel1))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(163, 163, 163)
										.addComponent(cautare_angajat, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(96, 96, 96).addComponent(orar_angajat,
												javax.swing.GroupLayout.PREFERRED_SIZE, 160,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(188, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(28, 28, 28).addComponent(log_out))
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(46, 46, 46).addComponent(jLabel1)))
						.addGap(74, 74, 74)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cautare_angajat, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(orar_angajat, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(125, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 3, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void cautare_angajatActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Cautare_Angajat ct = new Cautare_Angajat();
		ct.show();
		dispose();

	}

	private void orar_angajatActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String t = "Inspector";
		Afisare_info_angajati afs = new Afisare_info_angajati(t);
		afs.show();
		dispose();
	}

	private void log_outActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		LoginResurse lr = new LoginResurse();
		lr.show();
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Inspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Inspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Inspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Inspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Inspector().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton cautare_angajat;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton log_out;
	private javax.swing.JButton orar_angajat;
	// End of variables declaration
}
