/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poli14;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Costea Delia
 */
public class Modifica_Utilizatori extends javax.swing.JFrame {

	/**
	 * Creates new form Modifica_Utilizatori
	 */
	public Modifica_Utilizatori(String s) {
		initComponents(s);
		tabel_update(s);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String s) {

		jPanel1 = new javax.swing.JPanel();
		inapoi = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		cnp = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tabel2 = new javax.swing.JTable();
		nume = new javax.swing.JTextField();
		prenume = new javax.swing.JTextField();
		adresa = new javax.swing.JTextField();
		nr_tlf = new javax.swing.JTextField();
		email = new javax.swing.JTextField();
		iban = new javax.swing.JTextField();
		contact = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		data = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		adauga = new javax.swing.JButton();
		jLabel16 = new javax.swing.JLabel();
		editeaza = new javax.swing.JButton();
		jLabel17 = new javax.swing.JLabel();
		sterge = new javax.swing.JButton();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		functia = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(153, 255, 255));

		jPanel1.setBackground(new java.awt.Color(153, 255, 255));

		inapoi.setBackground(new java.awt.Color(153, 204, 255));
		inapoi.setText("Inapoi");
		inapoi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inapoiActionPerformed(evt);
			}
		});

		jLabel12.setText("CNP");

		jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
		jLabel13.setText("Modifica Utilizatori");

		cnp.setBackground(new java.awt.Color(204, 255, 255));
		cnp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cnpActionPerformed(evt);
			}
		});

		jLabel24.setText("Data angajarii");

		jScrollPane2.setBorder(null);

		tabel2.setBackground(new java.awt.Color(204, 255, 255));
		tabel2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null } },
				new String[] { "CNP", "Nume", "Prenume", "Adresa", "Nr_telefon", "Email", "Cont_IBAN", "Nr_Contact",
						"Data_Angajarii", "Functia" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		tabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tabel2MouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(tabel2);

		nume.setBackground(new java.awt.Color(204, 255, 255));
		nume.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				numeActionPerformed(evt);
			}
		});

		prenume.setBackground(new java.awt.Color(204, 255, 255));

		adresa.setBackground(new java.awt.Color(204, 255, 255));

		nr_tlf.setBackground(new java.awt.Color(204, 255, 255));

		email.setBackground(new java.awt.Color(204, 255, 255));

		iban.setBackground(new java.awt.Color(204, 255, 255));

		contact.setBackground(new java.awt.Color(204, 255, 255));

		jLabel14.setText("Nume");

		data.setBackground(new java.awt.Color(204, 255, 255));

		jLabel15.setText("Prenume");

		adauga.setBackground(new java.awt.Color(153, 204, 255));
		adauga.setText("Adauga");
		adauga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adaugaActionPerformed(evt, s);
			}
		});

		jLabel16.setText("Numar de telefon");

		editeaza.setBackground(new java.awt.Color(153, 204, 255));
		editeaza.setText("Editeaza");
		editeaza.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editeazaActionPerformed(evt, s);
			}
		});

		jLabel17.setText("Cont IBAN");

		sterge.setBackground(new java.awt.Color(153, 204, 255));
		sterge.setText("Sterge");
		sterge.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stergeActionPerformed(evt, s);
			}
		});

		jLabel20.setText("Functia");

		jLabel21.setText("Email");

		jLabel23.setText("Adresa");

		jLabel1.setText("Numar contact");

		functia.setBackground(new java.awt.Color(204, 255, 255));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(28, 28, 28)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 105,
														Short.MAX_VALUE)
												.addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(34, 34, 34)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(cnp).addComponent(nume).addComponent(prenume)
												.addComponent(adresa).addComponent(nr_tlf).addComponent(email)
												.addComponent(iban).addComponent(contact).addComponent(data)
												.addComponent(functia, javax.swing.GroupLayout.DEFAULT_SIZE, 140,
														Short.MAX_VALUE)))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(adauga)
										.addGap(18, 18, 18).addComponent(editeaza).addGap(18, 18, 18)
										.addComponent(sterge)))
								.addGap(48, 48, 48).addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
										848, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16).addComponent(inapoi)
								.addGap(375, 375, 375).addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE,
										287, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(29, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(inapoi))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(37, 37, 37)
										.addComponent(jLabel13)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(71, 71, 71)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel12).addComponent(cnp,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel14).addComponent(nume,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel15).addComponent(prenume,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel23)
												.addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel16)
												.addComponent(nr_tlf, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel21).addComponent(email,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel17).addComponent(iban,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel24))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel20).addComponent(functia,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(50, 50, 50).addComponent(
										jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(adauga).addComponent(editeaza).addComponent(sterge))
						.addContainerGap(48, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void cnpActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	Connection con1;
	PreparedStatement insert;

	private void tabel_update(String s) {
		int x;

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			insert = con1.prepareStatement("select* from utilizator");
			ResultSet rs = insert.executeQuery();
			ResultSetMetaData Rss = rs.getMetaData();
			x = Rss.getColumnCount();
			DefaultTableModel Df = (DefaultTableModel) tabel2.getModel();
			Df.setRowCount(0);
			int ok;
			if (s.equals("Administrator"))
				ok = 0;
			else
				ok = 1;
			while (rs.next()) {
				if (!rs.getString("Functia").equals("Administrator") || ok == 1) {
					Vector v2 = new Vector();
					for (int i = 1; i <= x; i++) {

						v2.add(rs.getString("CNP"));
						v2.add(rs.getString("Nume"));
						v2.add(rs.getString("Prenume"));
						v2.add(rs.getString("Adresa"));
						v2.add(rs.getString("Nr_telefon"));
						v2.add(rs.getString("Email"));
						v2.add(rs.getString("Cont_IBAN"));
						v2.add(rs.getString("Nr_Contact"));
						v2.add(rs.getString("Data_Angajarii"));
						v2.add(rs.getString("Functia"));

					}
					Df.addRow(v2);
				}
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void tabel2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel Df = (DefaultTableModel) tabel2.getModel();
		int selectedIndex = tabel2.getSelectedRow();
		cnp.setText(Df.getValueAt(selectedIndex, 0).toString());
		nume.setText(Df.getValueAt(selectedIndex, 1).toString());
		prenume.setText(Df.getValueAt(selectedIndex, 2).toString());
		adresa.setText(Df.getValueAt(selectedIndex, 3).toString());
		nr_tlf.setText(Df.getValueAt(selectedIndex, 4).toString());
		email.setText(Df.getValueAt(selectedIndex, 5).toString());
		iban.setText(Df.getValueAt(selectedIndex, 6).toString());
		contact.setText(Df.getValueAt(selectedIndex, 7).toString());
		data.setText(Df.getValueAt(selectedIndex, 8).toString());
		functia.setText(Df.getValueAt(selectedIndex, 9).toString());

	}

	private void numeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	Statement statement;

	private void stergeActionPerformed(java.awt.event.ActionEvent evt, String s) {
		// TODO add your handling code here:
		DefaultTableModel Df = (DefaultTableModel) tabel2.getModel();
		int selectedIndex = tabel2.getSelectedRow();

		try {

			int dialogResult = JOptionPane.showConfirmDialog(null, "Vrei sa stergi inregistrarea?", "Atentie!",
					JOptionPane.YES_NO_OPTION);
			if (dialogResult == JOptionPane.YES_OPTION) {

				Class.forName("com.mysql.jdbc.Driver");
				con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");

				statement = (Statement) con1.createStatement();

				int ok = 0;
				if ((functia.getText().equals("Administrator") || functia.getText().equals("Super Administrator"))
						&& s.equals("Super Administrator")) {
					ok = 1;

				} else if (!(functia.getText().equals("Administrator")
						&& !functia.getText().equals("Super Administrator"))) {
					ok = 1;
				}
				if (ok == 1) {
					statement.executeQuery("call drop_utilizator('" + cnp.getText() + "');");

					JOptionPane.showMessageDialog(this, "Inregistrare stearsa cu succes!");
				} else
					JOptionPane.showMessageDialog(this, "Nu aveti voie!");

				tabel_update(s);

				cnp.setText("");
				nume.setText("");
				prenume.setText("");
				adresa.setText("");
				nr_tlf.setText("");
				email.setText("");
				iban.setText("");
				contact.setText("");
				data.setText("");
				functia.setText("");

				cnp.requestFocus();

			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void editeazaActionPerformed(java.awt.event.ActionEvent evt, String s) {
		// TODO add your handling code here:DefaultTableModel Df = (DefaultTableModel)
		// tabel2.getModel();
		DefaultTableModel Df = (DefaultTableModel) tabel2.getModel();
		int selectedIndex = tabel2.getSelectedRow();
		long id = Long.parseLong(Df.getValueAt(selectedIndex, 0).toString());
		try {

			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");

			int p = 0;
			if (functia.getText().equals("Pacient")) {
				p = 1;
			}
			int ok = 0;
			if ((functia.getText().equals("Administrator") || functia.getText().equals("Super Administrator"))
					&& s.equals("Super Administrator")) {
				ok = 1;

			} else if (!(functia.getText().equals("Administrator")
					&& !functia.getText().equals("Super Administrator"))) {
				ok = 1;
			}
			if (ok == 1) {
				insert = con1.prepareStatement("update policlinica.utilizator SET CNP ='" + cnp.getText()
						+ "', Nume = '" + nume.getText() + "', Prenume ='" + prenume.getText() + "', Pacient =" + p
						+ ", Adresa ='" + adresa.getText() + "', Nr_telefon ='" + nr_tlf.getText() + "', Email ='"
						+ email.getText() + "', Cont_IBAN ='" + iban.getText() + "', Nr_Contact ='" + contact.getText()
						+ "', Data_Angajarii ='" + data.getText() + "', Functia ='" + functia.getText()
						+ "' where CNP ='" + id + "';");

				insert.executeUpdate();
				JOptionPane.showMessageDialog(this, "Inregistrare editata cu succes!");
			} else
				JOptionPane.showMessageDialog(this, "Nu aveti voie!");
			tabel_update(s);

			cnp.setText("");
			nume.setText("");
			prenume.setText("");
			adresa.setText("");
			nr_tlf.setText("");
			email.setText("");
			iban.setText("");
			contact.setText("");
			data.setText("");
			functia.setText("");

			cnp.requestFocus();

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void adaugaActionPerformed(java.awt.event.ActionEvent evt, String s) {
		DefaultTableModel Df = (DefaultTableModel) tabel2.getModel();
		int selectedIndex = tabel2.getSelectedRow();

		try {

			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");

			statement = (Statement) con1.createStatement();

			int p = 0;
			if (functia.getText().equals("Pacient")) {
				p = 1;
			}
			int ok = 0;
			if ((functia.getText().equals("Administrator") || functia.getText().equals("Super Administrator"))
					&& s.equals("Super Administrator")) {
				ok = 1;

			} else if (!(functia.getText().equals("Administrator")
					&& !functia.getText().equals("Super Administrator"))) {
				ok = 1;
			}
			if (ok == 1) {
				statement.executeQuery("call add_utilizator('" + cnp.getText() + "','" + nume.getText() + "','"
						+ prenume.getText() + "'," + p + ",'" + adresa.getText() + "','" + nr_tlf.getText() + "','"
						+ email.getText() + "','" + iban.getText() + "','" + contact.getText() + "','" + data.getText()
						+ "','" + functia.getText() + "');");

				JOptionPane.showMessageDialog(this, "Inregistrare adaugata cu succes!");
			} else
				JOptionPane.showMessageDialog(this, "Nu aveti voie!");
			tabel_update(s);

			cnp.setText("");
			nume.setText("");
			prenume.setText("");
			adresa.setText("");
			nr_tlf.setText("");
			email.setText("");
			iban.setText("");
			contact.setText("");
			data.setText("");
			functia.setText("");

			cnp.requestFocus();

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Modifica_Utilizatori.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void inapoiActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Administrator a = new Administrator();
		a.show();
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Modifica_Utilizatori.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Modifica_Utilizatori.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Modifica_Utilizatori.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Modifica_Utilizatori.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				String s = "Administrator";
				new Modifica_Utilizatori(s).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton adauga;
	private javax.swing.JTextField adresa;
	private javax.swing.JTextField cnp;
	private javax.swing.JTextField contact;
	private javax.swing.JTextField data;
	private javax.swing.JButton editeaza;
	private javax.swing.JTextField email;
	private javax.swing.JTextField functia;
	private javax.swing.JTextField iban;
	private javax.swing.JButton inapoi;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField nr_tlf;
	private javax.swing.JTextField nume;
	private javax.swing.JTextField prenume;
	private javax.swing.JButton sterge;
	private javax.swing.JTable tabel2;
	// End of variables declaration
}