/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poli14;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ToBy
 */
public class VizualizareRapoarte extends javax.swing.JFrame {

	/**
	 * Creates new form VizualizareRapoarte
	 */
	public VizualizareRapoarte(UserParola a, String t) {
		initComponents(a, t);
		tabel_update(a, t);
	}

	Connection con1;
	PreparedStatement insert;
	Statement statement;

	private void tabel_update(UserParola a, String t) {
		int x;

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			ResultSet rs2;
			if (t.equals("Medic")) {
				statement = con1.createStatement();
				rs2 = statement.executeQuery(
						"Select idMedic from medic m inner join angajat using (idMedic) inner join utilizator u using (idAngajat) where CNP ='"
								+ a.Parola + "';");
				rs2.next();
				insert = con1.prepareStatement("select* from raport where idMedic = " + rs2.getString("idMedic") + ";");
			} else if (t.equals("Asistent")) {
				statement = con1.createStatement();
				rs2 = statement.executeQuery(
						"Select idAsistent_Medical from Asistent_Medical am inner join angajat using (idAsistent_Medical) inner join utilizator u using (idAngajat) where CNP ='"
								+ a.Parola + "';");
				rs2.next();
				insert = con1.prepareStatement(
						"select* from raport where idAsistent = " + rs2.getString("idAsistent_Medical") + ";");

			}
			ResultSet rs = insert.executeQuery();
			ResultSetMetaData Rss = rs.getMetaData();
			x = Rss.getColumnCount();
			DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
			Df.setRowCount(0);

			while (rs.next()) {
				Vector v2 = new Vector();
				for (int i = 1; i <= x; i++) {
					ResultSet rs01 = statement.executeQuery(
							"Select Nume, Prenume from utilizator where CNP = '" + rs.getString("CNP") + "';");
					rs01.next();
					v2.add(rs01.getString("Nume"));
					v2.add(rs01.getString("Prenume"));
					ResultSet rs02 = statement
							.executeQuery("call policlinica.cautaCNP_medic(" + rs.getString("idMedic") + ");");
					rs02.next();
					v2.add(rs02.getString("Nume"));
					v2.add(rs02.getString("Prenume"));
					ResultSet rs03 = statement
							.executeQuery("call policlinica.cautaCNP_asistent(" + rs.getString("idAsistent") + ");");
					rs03.next();
					v2.add(rs03.getString("Nume"));
					v2.add(rs03.getString("Prenume"));
					v2.add(rs.getString("data_consult"));
					v2.add(rs.getString("simptome"));
					v2.add(rs.getString("Simptome"));
					v2.add(rs.getString("diagnostic"));
					v2.add(rs.getString("recomandari"));

				}
				Df.addRow(v2);
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(ListaMedici2.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(ListaMedici2.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(UserParola a, String t) {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		inapoi = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		npc = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		npc2 = new javax.swing.JTextField();
		simpt = new javax.swing.JTextField();
		na = new javax.swing.JTextField();
		investigatii = new javax.swing.JTextField();
		nm = new javax.swing.JTextField();
		data = new javax.swing.JTextField();
		nm2 = new javax.swing.JTextField();
		na2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		disagnostic = new javax.swing.JTextField();
		recom = new javax.swing.JTextField();
		completare = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(153, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
		jLabel1.setText("Rapoarte");

		inapoi.setBackground(new java.awt.Color(153, 204, 255));
		inapoi.setText("Inapoi");
		inapoi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inapoiActionPerformed(evt, a, t);
			}
		});

		jTable1.setBackground(new java.awt.Color(204, 255, 255));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null } },
				new String[] { "Nume Pacient", "Prenume Pacient", "Nume Medic", "Prenume Medic", "Nume Asistent",
						"Prenume Asistent", "Data", "Simptome", "Investigatii", "Diagnostic", "Recomandari" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel2.setText("Nume Pacient");

		npc.setBackground(new java.awt.Color(204, 255, 255));

		jLabel3.setText("Prenume Pacient");

		npc2.setBackground(new java.awt.Color(204, 255, 255));

		simpt.setBackground(new java.awt.Color(204, 255, 255));

		na.setBackground(new java.awt.Color(204, 255, 255));

		investigatii.setBackground(new java.awt.Color(204, 255, 255));

		nm.setBackground(new java.awt.Color(204, 255, 255));

		data.setBackground(new java.awt.Color(204, 255, 255));

		nm2.setBackground(new java.awt.Color(204, 255, 255));

		na2.setBackground(new java.awt.Color(204, 255, 255));

		jLabel4.setText("Nume Medic");

		jLabel5.setText("Prenume Medic");

		jLabel7.setText("Nume Asistent");

		jLabel8.setText("Prenume Asistent");

		jLabel9.setText("Data");

		jLabel10.setText("Investigatii");

		jLabel11.setText("Simptome");

		jLabel12.setText("Diagnostic");

		jLabel13.setText("Recomandari");

		disagnostic.setBackground(new java.awt.Color(204, 255, 255));

		recom.setBackground(new java.awt.Color(204, 255, 255));

		completare.setBackground(new java.awt.Color(153, 204, 255));
		completare.setText("Adaugare");
		completare.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				completareActionPerformed(evt, a, t);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												jPanel1Layout
														.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 101,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 81,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 91,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(39, 39, 39)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(npc2,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 211,
																		Short.MAX_VALUE)
																.addComponent(nm).addComponent(npc)))
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE,
																101, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel11,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(jLabel5,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jLabel7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						89,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel8,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jLabel9,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						101, Short.MAX_VALUE))
																		.addComponent(jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				101,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel13,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				101,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(0, 0, Short.MAX_VALUE)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(disagnostic)
														.addComponent(na, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(na2, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(data, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(simpt, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(investigatii,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(nm2, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(recom, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 211,
																Short.MAX_VALUE))))
										.addGap(45, 45, 45)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(25, 25, 25))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(6, 6, 6).addComponent(inapoi)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(590, 590, 590))))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(201, 201, 201).addComponent(completare).addGap(0,
						0, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(17, 17, 17)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(inapoi).addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(npc, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(npc2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(nm2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel9).addComponent(data,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(simpt, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel11))
										.addGap(9, 9, 9)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(investigatii, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel10))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(disagnostic, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel12))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(recom, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel13)))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(completare).addContainerGap(23, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();

	}// </editor-fold>

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
		int selectedIndex = jTable1.getSelectedRow();
		nm.setText(Df.getValueAt(selectedIndex, 2).toString());
		nm2.setText(Df.getValueAt(selectedIndex, 3).toString());

	}

	private void inapoiActionPerformed(java.awt.event.ActionEvent evt, UserParola a, String t) {
		// TODO add your handling code here:
		if (t.equals("Medic")) {
			Medic m = new Medic(a);
			m.show();
		} else if (t.equals("Asistent")) {

			AsistentMedical am = new AsistentMedical(a);
			am.show();
		}
		dispose();

	}

	private void completareActionPerformed(java.awt.event.ActionEvent evt, UserParola a, String t) {
		// TODO add your handling code here:

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con1 = DriverManager.getConnection("jdbc:mysql://localhost/policlinica", "root", "1234");
			insert = con1.prepareStatement(
					"insert into raport(CNP ,idMedic ,idAsistent,data_consult ,simptome ,diagnostic,recomandari )values(?,?,?,?,?,?,?)");
			statement = con1.createStatement();
			ResultSet rs = statement.executeQuery("Select CNP from utilizator where Nume = '" + npc.getText()
					+ "' and Prenume = '" + npc2.getText() + "';");
			rs.next();
			insert.setString(1, rs.getString("CNP"));
			ResultSet rs2 = statement.executeQuery(
					"Select idMedic from medic m inner join angajat using (idMedic) inner join utilizator using (idAngajat) where Nume = '"
							+ nm.getText() + "' and Prenume = '" + nm2.getText() + "';");
			rs2.next();
			insert.setString(2, rs2.getString("idMedic"));
			ResultSet rs3 = statement.executeQuery(
					"Select idAsistent_Medical from Asistent_Medical am inner join angajat using (idAsistent_Medical) inner join utilizator u using (idAngajat) where u.Nume = '"
							+ na.getText() + "' and Prenume = '" + na2.getText() + "';");
			rs3.next();
			insert.setString(3, rs3.getString("idAsistent_Medical"));// ordinea din tabele
			insert.setString(4, data.getText());
			insert.setString(5, simpt.getText());
			insert.setString(6, disagnostic.getText());
			insert.setString(7, recom.getText());
			insert.executeUpdate();

			JOptionPane.showMessageDialog(this, "Adaugat");
			tabel_update(a, t);

			nm.setText("");
			nm2.setText("");
			npc2.setText("");
			npc.setText("");
			na.setText("");
			na2.setText("");
			data.setText("");
			simpt.setText("");
			disagnostic.setText("");
			investigatii.setText("");
			recom.setText("");

			npc.requestFocus();

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}

		catch (SQLException ex) {
			Logger.getLogger(Inregistrare_medic.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VizualizareRapoarte.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VizualizareRapoarte.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VizualizareRapoarte.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VizualizareRapoarte.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UserParola a = new UserParola("popescu.maria@yahoo.com", "1950822342352");
				String s = "Medic";
				new VizualizareRapoarte(a, s).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton completare;
	private javax.swing.JTextField data;
	private javax.swing.JTextField disagnostic;
	private javax.swing.JButton inapoi;
	private javax.swing.JTextField investigatii;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField na;
	private javax.swing.JTextField na2;
	private javax.swing.JTextField nm;
	private javax.swing.JTextField nm2;
	private javax.swing.JTextField npc;
	private javax.swing.JTextField npc2;
	private javax.swing.JTextField recom;
	private javax.swing.JTextField simpt;
	// End of variables declaration
}
